### ISSUE TITLE
Nemo-seahorse: Nothing happens when trying to encrypt folder

### ISSUE THREAD

**Issue by petter3k** [linuxmint/nemo-extensions#42] opened 2014-01-25 11:14 UTC
Hi,

nothing happens after I have created my keys and trying to encrypt a folder.

After I press "ok" theres no change in the folder, or no progress bar or anything to imply that something is happening in the background. Conky also reports no new processes that are running in the background.

**Comment by teeedubb** [comment] 2015-09-05 12:06
Hi,
Any updates on this issue? Ive upgraded libcryptui to 3.12.2 and the problem still persists.

**Comment by gneb962** [comment] 2017-04-09 18:06
Still not working.

**Comment by leigh123linux** [comment] 2017-04-09 18:13
Duplicate of #205

**Closed by leigh123linux** 2017-04-09 18:13 UTC
