### ISSUE TITLE
nemo-preview-start crashes on launch (Manjaro, gnome, mutter, wayland)

### ISSUE THREAD

**Issue by t00** [linuxmint/nemo-extensions#491] opened 2023-08-06 07:02 UTC
It might be some misconfiguration or wayland issue but I cannot seem to make it work (i just installed preview).

```
Command line: /usr/lib/nemo-preview/nemo-preview-start
Message: Process 3204566 (nemo-preview-st) of user 1000 dumped core.
        
        Stack trace of thread 3204566:
        #0  0x0000000000000000 n/a (n/a + 0x0)
        #1  0x00007ffc38f598c8 n/a (n/a + 0x0)
        ELF object binary architecture: AMD x86-64

```
backtrace:

```

#0  0x0000000000000000 in  ()
#1  0x00007febb51412da in g_hash_table_lookup_node (hash_return=<synthetic pointer>, key=0x7ffc38f595d8, hash_table=0x55b2bd6a44c0<error reading variable: Cannot access memory at address 0x100000000>)
    at ../glib/glib/ghash.c:474
#2  g_hash_table_lookup (hash_table=0x55b2bd6a44c0<error reading variable: Cannot access memory at address 0x100000000>, key=key@entry=0x7ffc38f595d8) at ../glib/glib/ghash.c:1541
#3  0x00007febb47be790 in gdk_x11_window_lookup_for_display (display=display@entry=0x55b2bd662c90, window=<optimized out>, window@entry=0) at ../gtk/gdk/x11/gdkxid.c:105
#4  0x00007febb47be843 in gdk_x11_window_foreign_new_for_display (display=0x55b2bd662c90, window=0) at ../gtk/gdk/x11/gdkwindow-x11.c:1244
#5  0x00007febb3e384f6 in  () at /usr/lib/libffi.so.8
#6  0x0000000000000007 in  ()
#7  0x00007ffc38f598c8 in  ()
#8  0x00007ffc38f597e0 in  ()
#9  0x00007febb3e34f5e in  () at /usr/lib/libffi.so.8
#10 0x00000000af0d4b0c in  ()
#11 0x0000000000000000 in  ()
```

**Comment by leigh123linux** [comment] 2023-08-06 08:53
Duplicate of #482

**Closed by leigh123linux** 2023-08-06 08:53 UTC
