### ISSUE TITLE
Feature Request - nemo-preview - allow arrow key navigation of directory contents / search results whilst preview window has focus

### ISSUE THREAD

**Issue by smurphos** [linuxmint/nemo-extensions#369] opened 2020-08-06 06:28 UTC
Current nemo-preview version
`nemo-preview/ulyana,now 4.6.0+ulyana amd64 [installed]`

Hi, currently if one wants to preview a selection of files from a  directory or a nemo search the workflow is 

Select a file > space to preview > escape to exit preview > arrow key to select another file > space to preview > escape to exit preview > etc etc

It would be nice if it was possible to use arrow keys to navigate the directory or search results list without having to close the preview window and have the preview window update automatically.

**Comment by hamiltont** [comment] 2020-09-06 15:09
duplicate of #154

**Closed** 2020-09-07 07:44 UTC
